title: Dhanan Pradipta # your name (or website title) here
logo: "/images/fotogithub.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Interested to analyze and visualize the data, and sometimes making a machine learning model. full-time learner
  reach me out at :
  <br><br>
  <a href="https://www.linkedin.com/in/dhananpradipta/">My LinkedIn Profile</a>
  <a href="https://github.com/dhanandipta/data_science_project/">Github Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
